### ISSUE TITLE
Building site requires Python 2

### ISSUE THREAD

**Issue by lordmauve** [PyconUK/pyconuk.org#127]
Attempting to install the build dependencies for the site under Python 3.4, I get this message:

```
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\Users\zky39or\AppData\Local\Temp\pip-build-ixl0b4r6\wok\setup.py", line 37, in <module>
    scripts=['scripts/wok'],
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "C:\Python34\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\Python34\lib\site-packages\setuptools\command\egg_info.py", line 75, in finalize_options
    self.egg_version = self.tagged_version()
  File "C:\Python34\lib\site-packages\setuptools\command\egg_info.py", line 165, in tagged_version
    return safe_version(version + self.vtags)
TypeError: can't concat bytes to str

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\zky39or\
AppData\Local\Temp\pip-build-ixl0b4r6\wok
```

Presumably wok doesn't support Python 3.

**Comment by snim2** [comment]
I would guess so. I've always built the site with `2.7`. The travis config for Wok only tests `2.7`:

https://github.com/mythmon/wok/blob/master/.travis.yml

:-(

I'm going to close this as the issue lies upstream.

**Comment by ntoll** [comment]
@snim2 I think @lordmauve is making a good point here. PyCon UK should be Python 3-able. Re-opening for the sake of visibility.

**Comment by nceder** [comment]
I had the same issue and looked into it at the time... wok is the issue,
and it's not Python 3 yet. Nor is there AFAICT any real movement to make it
happy with Python3.

On 26 August 2015 at 09:13, Nicholas Tollervey notifications@github.com
wrote:

> @snim2 https://github.com/snim2 I think @lordmauve
> https://github.com/lordmauve is making a good point here. PyCon UK
> should be Python 3-able. Re-opening for the sake of visibility.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/pyconuk.org/issues/127#issuecomment-135035452
> .

## 

Naomi Ceder
https://plus.google.com/u/0/111396744045017339164/about

**Comment by zeth** [comment]
The first time I tried to use wok I was using a machine with only Python 3
installed and ran into the same issue.

This reminds me that at that time, we had a suggestion that George or
someone could lead a sprint about either fixing wok for Python3 and/or
testing our content in sphinx.

**Comment by jneves** [comment]
Just a heads up that I'm working on this. Hopefully someone can finish the work in the sprint tomorrow.

Requirements changes that work:
-e git+https://github.com/tBaxter/vobject.git@5bdf21751a6f443045e05db862e00be5bbd006f3#egg=vobject
-e git+https://github.com/jneves/wok.git@ad9145705014b58a23165d920aebc226818a6834#egg=wok

I'm working on LinkChecker at the moment. According to https://github.com/wummel/linkchecker/blob/master/doc/python3.txt there's a solution for all dependencies of it.

No other dependencies actually fail to install, so hopefully we can get there.

**Comment by doismellburning** [comment]
LinkChecker! <3

**Comment by jneves** [comment]
Current work is at https://github.com/jneves/pyconuk.org/tree/python3. I'm pretty sure I'm not going to be able to finish linkchecker.

**Comment by jneves** [comment]
I was mistaken, as linkchecker is actually commented out and not used, it's actually fixed ;).

**Comment by jneves** [comment]
Ok, it's mostly working at: https://github.com/jneves/pyconuk.org/tree/python3 - I seem to have broken the hooks that generate the flat schedule and whateves generates the ics. If I find a way of fixing that, I'll do a pull request.

**Comment by inglesp** [comment]
Hey @jneves -- keep up the good work!

**Comment by jneves** [comment]
Yes, fixed the hooks :)
